# Generated by Django 5.0.1 on 2024-01-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
