# Generated by Django 5.0.1 on 2024-01-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_product_stock_alter_product_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vat',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19, null=True),
        ),
    ]
